### ISSUE TITLE
Scroll bar issue

### ISSUE THREAD

**Issue by JsutterIntulse** [intulse/intulse-app-beta#8]
**Describe the bug [required]**
If a drop down list exceeds the height of the screen and you try to use the side scroll bar to scroll down through the list it will cause the screen to jump back to the top.

**To Reproduce [required]**
1. Go to admin - Extension monitoring Access
2. Ensure there are enough extensions to produce a scroll bar
3. click on Extension drop down list
4. use right side scroll bar to scroll down
5. Scroll to bottom of list

**Expected behavior [required]**
Screen stays at location where scroll bar is un-clicked

**Actual behavior [required]**
Screen navigates back to top of list

**Desktop (please complete the following information):**
Windows
Chrome

**Comment by gdalam** [comment]
@darrenhollick I'm not sure how we're supposed to fix this. By default, `autoClose` on NgbDropdown is true, which is why any click after opening the dropdown will close it. Here are the `autoClose` options

true - the dropdown will close on both outside and inside (menu) clicks.
false - the dropdown can only be closed manually via close() or toggle() methods.
"inside" - the dropdown will close on inside menu clicks, but not outside clicks.
"outside" - the dropdown will close only on the outside clicks and not on menu clicks.

True is what we want, except it detects clicks on the scrollbar. I have two ideas:

1 Test if we can make the scroll bar appear next to the list (instead of the entire browser window) - maybe this would work? Not sure how to do that
2 Intercept clicks and check if they're on the scrollbar (not sure if this is possible without checking the mouse coordinates)

**Comment by darrenhollick** [comment]
Now when you click in the filter box it also closes the dropdown
